/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GhostWritingServicesRouteImport } from './routes/ghost-writing-services'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesArticleBlogWritingRouteImport } from './routes/services/article-blog-writing'
import { Route as ServicesAudioBookPublishingRouteImport } from './routes/services/audio-book-publishing'
import { Route as ServicesAuthorWebsiteRouteImport } from './routes/services/author-website'
import { Route as ServicesBookCoverDesignRouteImport } from './routes/services/book-cover-design'
import { Route as ServicesBookFormattingRouteImport } from './routes/services/book-formatting'
import { Route as ServicesBookIllustrationsRouteImport } from './routes/services/book-illustrations'
import { Route as ServicesBookMarketingRouteImport } from './routes/services/book-marketing'
import { Route as ServicesBookPrintingRouteImport } from './routes/services/book-printing'
import { Route as ServicesBookPublishingRouteImport } from './routes/services/book-publishing'
import { Route as ServicesEditingProofreadingRouteImport } from './routes/services/editing-proofreading'
import { Route as ServicesGhostWritingRouteImport } from './routes/services/ghost-writing'
import { Route as ServicesVideoBookTrailerRouteImport } from './routes/services/video-book-trailer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GhostWritingServicesRoute = GhostWritingServicesRouteImport.update({
  id: '/ghost-writing-services',
  path: '/ghost-writing-services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesArticleBlogWritingRoute =
  ServicesArticleBlogWritingRouteImport.update({
    id: '/services/article-blog-writing',
    path: '/services/article-blog-writing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAudioBookPublishingRoute =
  ServicesAudioBookPublishingRouteImport.update({
    id: '/services/audio-book-publishing',
    path: '/services/audio-book-publishing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAuthorWebsiteRoute = ServicesAuthorWebsiteRouteImport.update({
  id: '/services/author-website',
  path: '/services/author-website',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBookCoverDesignRoute = ServicesBookCoverDesignRouteImport.update({
  id: '/services/book-cover-design',
  path: '/services/book-cover-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBookFormattingRoute = ServicesBookFormattingRouteImport.update({
  id: '/services/book-formatting',
  path: '/services/book-formatting',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBookIllustrationsRoute =
  ServicesBookIllustrationsRouteImport.update({
    id: '/services/book-illustrations',
    path: '/services/book-illustrations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBookMarketingRoute = ServicesBookMarketingRouteImport.update({
  id: '/services/book-marketing',
  path: '/services/book-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBookPrintingRoute = ServicesBookPrintingRouteImport.update({
  id: '/services/book-printing',
  path: '/services/book-printing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBookPublishingRoute = ServicesBookPublishingRouteImport.update({
  id: '/services/book-publishing',
  path: '/services/book-publishing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEditingProofreadingRoute =
  ServicesEditingProofreadingRouteImport.update({
    id: '/services/editing-proofreading',
    path: '/services/editing-proofreading',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesGhostWritingRoute = ServicesGhostWritingRouteImport.update({
  id: '/services/ghost-writing',
  path: '/services/ghost-writing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVideoBookTrailerRoute =
  ServicesVideoBookTrailerRouteImport.update({
    id: '/services/video-book-trailer',
    path: '/services/video-book-trailer',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/ghost-writing-services': typeof GhostWritingServicesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/testimonials': typeof TestimonialsRoute
  '/services/article-blog-writing': typeof ServicesArticleBlogWritingRoute
  '/services/audio-book-publishing': typeof ServicesAudioBookPublishingRoute
  '/services/author-website': typeof ServicesAuthorWebsiteRoute
  '/services/book-cover-design': typeof ServicesBookCoverDesignRoute
  '/services/book-formatting': typeof ServicesBookFormattingRoute
  '/services/book-illustrations': typeof ServicesBookIllustrationsRoute
  '/services/book-marketing': typeof ServicesBookMarketingRoute
  '/services/book-printing': typeof ServicesBookPrintingRoute
  '/services/book-publishing': typeof ServicesBookPublishingRoute
  '/services/editing-proofreading': typeof ServicesEditingProofreadingRoute
  '/services/ghost-writing': typeof ServicesGhostWritingRoute
  '/services/video-book-trailer': typeof ServicesVideoBookTrailerRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/ghost-writing-services': typeof GhostWritingServicesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/testimonials': typeof TestimonialsRoute
  '/services/article-blog-writing': typeof ServicesArticleBlogWritingRoute
  '/services/audio-book-publishing': typeof ServicesAudioBookPublishingRoute
  '/services/author-website': typeof ServicesAuthorWebsiteRoute
  '/services/book-cover-design': typeof ServicesBookCoverDesignRoute
  '/services/book-formatting': typeof ServicesBookFormattingRoute
  '/services/book-illustrations': typeof ServicesBookIllustrationsRoute
  '/services/book-marketing': typeof ServicesBookMarketingRoute
  '/services/book-printing': typeof ServicesBookPrintingRoute
  '/services/book-publishing': typeof ServicesBookPublishingRoute
  '/services/editing-proofreading': typeof ServicesEditingProofreadingRoute
  '/services/ghost-writing': typeof ServicesGhostWritingRoute
  '/services/video-book-trailer': typeof ServicesVideoBookTrailerRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/ghost-writing-services': typeof GhostWritingServicesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/testimonials': typeof TestimonialsRoute
  '/services/article-blog-writing': typeof ServicesArticleBlogWritingRoute
  '/services/audio-book-publishing': typeof ServicesAudioBookPublishingRoute
  '/services/author-website': typeof ServicesAuthorWebsiteRoute
  '/services/book-cover-design': typeof ServicesBookCoverDesignRoute
  '/services/book-formatting': typeof ServicesBookFormattingRoute
  '/services/book-illustrations': typeof ServicesBookIllustrationsRoute
  '/services/book-marketing': typeof ServicesBookMarketingRoute
  '/services/book-printing': typeof ServicesBookPrintingRoute
  '/services/book-publishing': typeof ServicesBookPublishingRoute
  '/services/editing-proofreading': typeof ServicesEditingProofreadingRoute
  '/services/ghost-writing': typeof ServicesGhostWritingRoute
  '/services/video-book-trailer': typeof ServicesVideoBookTrailerRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/ghost-writing-services'
    | '/portfolio'
    | '/privacy-policy'
    | '/terms-of-use'
    | '/testimonials'
    | '/services/article-blog-writing'
    | '/services/audio-book-publishing'
    | '/services/author-website'
    | '/services/book-cover-design'
    | '/services/book-formatting'
    | '/services/book-illustrations'
    | '/services/book-marketing'
    | '/services/book-printing'
    | '/services/book-publishing'
    | '/services/editing-proofreading'
    | '/services/ghost-writing'
    | '/services/video-book-trailer'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/ghost-writing-services'
    | '/portfolio'
    | '/privacy-policy'
    | '/terms-of-use'
    | '/testimonials'
    | '/services/article-blog-writing'
    | '/services/audio-book-publishing'
    | '/services/author-website'
    | '/services/book-cover-design'
    | '/services/book-formatting'
    | '/services/book-illustrations'
    | '/services/book-marketing'
    | '/services/book-printing'
    | '/services/book-publishing'
    | '/services/editing-proofreading'
    | '/services/ghost-writing'
    | '/services/video-book-trailer'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/ghost-writing-services'
    | '/portfolio'
    | '/privacy-policy'
    | '/terms-of-use'
    | '/testimonials'
    | '/services/article-blog-writing'
    | '/services/audio-book-publishing'
    | '/services/author-website'
    | '/services/book-cover-design'
    | '/services/book-formatting'
    | '/services/book-illustrations'
    | '/services/book-marketing'
    | '/services/book-printing'
    | '/services/book-publishing'
    | '/services/editing-proofreading'
    | '/services/ghost-writing'
    | '/services/video-book-trailer'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GhostWritingServicesRoute: typeof GhostWritingServicesRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ServicesArticleBlogWritingRoute: typeof ServicesArticleBlogWritingRoute
  ServicesAudioBookPublishingRoute: typeof ServicesAudioBookPublishingRoute
  ServicesAuthorWebsiteRoute: typeof ServicesAuthorWebsiteRoute
  ServicesBookCoverDesignRoute: typeof ServicesBookCoverDesignRoute
  ServicesBookFormattingRoute: typeof ServicesBookFormattingRoute
  ServicesBookIllustrationsRoute: typeof ServicesBookIllustrationsRoute
  ServicesBookMarketingRoute: typeof ServicesBookMarketingRoute
  ServicesBookPrintingRoute: typeof ServicesBookPrintingRoute
  ServicesBookPublishingRoute: typeof ServicesBookPublishingRoute
  ServicesEditingProofreadingRoute: typeof ServicesEditingProofreadingRoute
  ServicesGhostWritingRoute: typeof ServicesGhostWritingRoute
  ServicesVideoBookTrailerRoute: typeof ServicesVideoBookTrailerRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghost-writing-services': {
      id: '/ghost-writing-services'
      path: '/ghost-writing-services'
      fullPath: '/ghost-writing-services'
      preLoaderRoute: typeof GhostWritingServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/article-blog-writing': {
      id: '/services/article-blog-writing'
      path: '/services/article-blog-writing'
      fullPath: '/services/article-blog-writing'
      preLoaderRoute: typeof ServicesArticleBlogWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/audio-book-publishing': {
      id: '/services/audio-book-publishing'
      path: '/services/audio-book-publishing'
      fullPath: '/services/audio-book-publishing'
      preLoaderRoute: typeof ServicesAudioBookPublishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/author-website': {
      id: '/services/author-website'
      path: '/services/author-website'
      fullPath: '/services/author-website'
      preLoaderRoute: typeof ServicesAuthorWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/book-cover-design': {
      id: '/services/book-cover-design'
      path: '/services/book-cover-design'
      fullPath: '/services/book-cover-design'
      preLoaderRoute: typeof ServicesBookCoverDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/book-formatting': {
      id: '/services/book-formatting'
      path: '/services/book-formatting'
      fullPath: '/services/book-formatting'
      preLoaderRoute: typeof ServicesBookFormattingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/book-illustrations': {
      id: '/services/book-illustrations'
      path: '/services/book-illustrations'
      fullPath: '/services/book-illustrations'
      preLoaderRoute: typeof ServicesBookIllustrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/book-marketing': {
      id: '/services/book-marketing'
      path: '/services/book-marketing'
      fullPath: '/services/book-marketing'
      preLoaderRoute: typeof ServicesBookMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/book-printing': {
      id: '/services/book-printing'
      path: '/services/book-printing'
      fullPath: '/services/book-printing'
      preLoaderRoute: typeof ServicesBookPrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/book-publishing': {
      id: '/services/book-publishing'
      path: '/services/book-publishing'
      fullPath: '/services/book-publishing'
      preLoaderRoute: typeof ServicesBookPublishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/editing-proofreading': {
      id: '/services/editing-proofreading'
      path: '/services/editing-proofreading'
      fullPath: '/services/editing-proofreading'
      preLoaderRoute: typeof ServicesEditingProofreadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ghost-writing': {
      id: '/services/ghost-writing'
      path: '/services/ghost-writing'
      fullPath: '/services/ghost-writing'
      preLoaderRoute: typeof ServicesGhostWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/video-book-trailer': {
      id: '/services/video-book-trailer'
      path: '/services/video-book-trailer'
      fullPath: '/services/video-book-trailer'
      preLoaderRoute: typeof ServicesVideoBookTrailerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GhostWritingServicesRoute: GhostWritingServicesRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  TestimonialsRoute: TestimonialsRoute,
  ServicesArticleBlogWritingRoute: ServicesArticleBlogWritingRoute,
  ServicesAudioBookPublishingRoute: ServicesAudioBookPublishingRoute,
  ServicesAuthorWebsiteRoute: ServicesAuthorWebsiteRoute,
  ServicesBookCoverDesignRoute: ServicesBookCoverDesignRoute,
  ServicesBookFormattingRoute: ServicesBookFormattingRoute,
  ServicesBookIllustrationsRoute: ServicesBookIllustrationsRoute,
  ServicesBookMarketingRoute: ServicesBookMarketingRoute,
  ServicesBookPrintingRoute: ServicesBookPrintingRoute,
  ServicesBookPublishingRoute: ServicesBookPublishingRoute,
  ServicesEditingProofreadingRoute: ServicesEditingProofreadingRoute,
  ServicesGhostWritingRoute: ServicesGhostWritingRoute,
  ServicesVideoBookTrailerRoute: ServicesVideoBookTrailerRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
